language: csharp
mono: none
dotnet: 3.0
dist: xenial

addons:
  sonarcloud:
    organization: "4a55b61e6429536b76bcb2939f2f0308613a0851"
    token:
      secure: "$SONAR_KEY"

install:
  # - dotnet tool install --global dotnet-sonarscanner --version 4.7.1
  
before_script:
  # - export PATH=${PATH}:${HOME}/.dotnet/tool"
  
jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.sonar/cache'

script:
 - dotnet restore
 - dotnet test Df.Magalu.Challenge.Tests/Df.Magalu.Challenge.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 - dotnet build
 - sonar-scanner

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master